### PR TITLE
Added a recursive version of the script.

### PR DESCRIPTION
**Pull request by sylvainbeo**

### CODE REVIEW

**Comment by 3nids** [comment]
did you modify the original script, if not can you discard the changes?

otherwise, I'd say merge this and see how it works :)

**Comment by sylvainbeo** [comment]
I had converted the tabs in spaces. But just revert that change.

**Comment by 3nids** [comment]
great, thanks!

**Comment by m-kuhn** [comment]
I like the tab to space conversion.
@3nids do you prefer tabs or is it ok for you if we change that?

**Comment by 3nids** [comment]
yeah I like tabs. But I like consistency too. feel free, be happy :)

**Comment by m-kuhn** [comment]
Let's declare spaces the standard, with [the power of a stackoverflow answer](http://stackoverflow.com/a/18962634/2319028) :wink:

**Comment by 3nids** [comment]
ok let's revert the revert.

**Comment by m-kuhn** [comment]
it's all pep8'ed with c98890429e6f592b2084e85d9cf1ffff72047cc1 
testing welcome

**Pull request merged**
